name: Deploy to GitHub Pages

on:
  push:
    paths:
      - 'index.html'  # Trigger only when index.html changes
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Upload all files (including index.html)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
